/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.keuda.view;

import com.keuda.exception.KeudaException;
import com.keuda.model.IkuProgram;
import com.keuda.model.ProgramDipa;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class IkuProgramDialog extends javax.swing.JDialog {
    
    
    IkuProgramPanel k_ikuPanel;
    MainForm k_mainForm;
    long sessionId;
    IkuProgram k_iprog;
    ProgramDipaListDialog k_dipaList;
    boolean add = false;
    ProgramDipa prodi;
    /**
     * Creates new form IkuProgramDialog
     */
    public IkuProgramDialog(IkuProgramPanel ikuPanel, boolean modal) {
        super(ikuPanel.k_mainForm, modal);
        
        initComponents();
        k_ikuPanel = ikuPanel;
        sessionId = k_ikuPanel.sessionId;
        k_iprog = new IkuProgram();
        k_mainForm = ikuPanel.k_mainForm;
        setLocationRelativeTo(null);
        txtIprog.setWrapStyleWord(true);
        txtIprog.setLineWrap(true);
        txtIprogDipa.setEditable(false);
        add = true;
        
    }
    
    public IkuProgramDialog(IkuProgram iprog, IkuProgramPanel ikuPanel, boolean modal) {
        super(ikuPanel.k_mainForm, modal);
        
        initComponents();
        k_ikuPanel = ikuPanel;
        sessionId = k_ikuPanel.sessionId;
        k_iprog = iprog;
        prodi = k_iprog.getDipa();
        prodi.setView(prodi.VIEW_PROGRAM);
        txtIprogDipa.setText(""+prodi);
        txtNoIku.setText(""+k_iprog.getNrIku());
        txtIprog.setText(k_iprog.getIku());
        
        txtIprog.setWrapStyleWord(true);
        txtIprog.setLineWrap(true);
        btn_browse.setEnabled(false);
        txtNoIku.setEditable(false);
        setLocationRelativeTo(null);
        txtIprogDipa.setEditable(false);
        add = false;
    }
    
    
    
    public void ambilData(){
        k_iprog.setDipa(prodi);
        k_iprog.setNrIku(Integer.valueOf(txtNoIku.getText()));
        k_iprog.setIku(txtIprog.getText());
    }
    
    public void updateData(){
        k_iprog.setIku(txtIprog.getText());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIprogDipa = new javax.swing.JTextField();
        btn_browse = new javax.swing.JButton();
        txtNoIku = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtIprog = new javax.swing.JTextArea();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("IKU Program"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Program DIPA :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nomor Iku :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Iku Program :");

        btn_browse.setText("...");
        btn_browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_browseActionPerformed(evt);
            }
        });

        txtIprog.setColumns(20);
        txtIprog.setRows(5);
        jScrollPane1.setViewportView(txtIprog);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIprogDipa, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_browse))
                            .addComponent(txtNoIku, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIprogDipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNoIku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batal)
                    .addComponent(btn_simpan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_browseActionPerformed
        k_dipaList = new ProgramDipaListDialog(k_mainForm);
        
        k_dipaList.setVisible(true);
        
        prodi = k_dipaList.getProgramDipa();
        txtIprogDipa.setText(""+prodi);
    }//GEN-LAST:event_btn_browseActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        if(add){
            if(txtIprogDipa.getText().trim().equals("") || txtIprogDipa.getText() == null){
                JOptionPane.showMessageDialog(this, "Kolom Program Dipa tidak boleh kosong.", "Kesalahan", JOptionPane.ERROR_MESSAGE);

            }else if(txtNoIku.getText().trim().equals("") || txtNoIku.getText() == null){
                JOptionPane.showMessageDialog(this, "Kolom Nomor IKU tidak boleh kosong.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }else if(txtIprog.getText().trim().equals("") || txtIprog.getText() == null){
                JOptionPane.showMessageDialog(this, "Kolom Iku tidak boleh kosong.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }else{
                ambilData();
                try {
                    k_ikuPanel.save(k_iprog, add);
                } catch (KeudaException ex) {
                    Logger.getLogger(IkuProgramDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            }
        }else{
            if(txtIprogDipa.getText().trim().equals("") || txtIprogDipa.getText() == null){
                JOptionPane.showMessageDialog(this, "Kolom Program Dipa tidak boleh kosong.", "Kesalahan", JOptionPane.ERROR_MESSAGE);

            }else if(txtNoIku.getText().trim().equals("") || txtNoIku.getText() == null){
                JOptionPane.showMessageDialog(this, "Kolom Nomor IKU tidak boleh kosong.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }else if(txtIprog.getText().trim().equals("") || txtIprog.getText() == null){
                JOptionPane.showMessageDialog(this, "Kolom Iku tidak boleh kosong.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }else{
                updateData();
                try {
                    k_ikuPanel.save(k_iprog, add);
                    
                } catch (KeudaException ex) {
                    Logger.getLogger(IkuProgramDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                dispose();
            }
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_browse;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtIprog;
    private javax.swing.JTextField txtIprogDipa;
    private javax.swing.JTextField txtNoIku;
    // End of variables declaration//GEN-END:variables
}
