/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.keuda.view;

import com.keuda.exception.KeudaException;
import com.keuda.model.IndikatorKegiatan;
import com.keuda.model.KegiatanDipa;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author client
 */
public class IndikatorKegiatanCreateUpdate extends javax.swing.JDialog {

    /**
     * Creates new form IndikatorKegiatanCreateUpdate
     */
    IndikatorKegiatan k_inke;
    boolean isNew = false;
    IndikatorKegiatanDipaPanel k_panel;
    KegiatanDipaListDialog k_dipaList;
    KegiatanDipa k_kedip;
    
    
    public IndikatorKegiatanCreateUpdate(IndikatorKegiatanDipaPanel mainForm, boolean modal) {
        this(mainForm, null);
    }

    public IndikatorKegiatanCreateUpdate(IndikatorKegiatanDipaPanel mainForm, IndikatorKegiatan inke) {
        super(mainForm.k_mainForm, "Form Isian Indikator Kegiatan", true);
        
        initComponents();
        setResizable(false);
        if(inke==null){
            k_inke = new IndikatorKegiatan();
            isNew = true;
        }else{
            
            k_inke = inke;
            
            System.out.println();
            
            System.out.println(k_inke.getNrindikator());
            System.out.println(k_inke.getIndikator());
            
            txt_nrIndikator.setEditable(false);
            btnBrowse.setEnabled(false);
            
            txt_Indikator.setText(k_inke.getIndikator());
            txt_nrIndikator.setText(""+k_inke.getNrindikator());
            
            txt_Kedip.setText(""+k_inke.getK_kedip().getProgramDipa().getProgram().getProgramName());
            isNew = false;
        }
//        Dimension dim = mainForm.k_mainForm.getSize();
//
//        // Determine the new location of the window
//        int w = this.getSize().width;
//        int h = this.getSize().height;
//        int x = (dim.width-w)/2;
//        int y = (dim.height-h)/2;
//
//        // Move the window
//        this.setLocation(x, y);
//        setLocationRelativeTo(mainForm);
        txt_Indikator.setLineWrap(true);
        txt_Indikator.setWrapStyleWord(true);
        k_panel = mainForm;
        
    }
    
    void getData(){
        
        if(txt_Kedip.getText().trim().equals("") || txt_Kedip.getText() == null){
            JOptionPane.showMessageDialog(this, "Harus Memilih Kegiatan Dipa", "Eror", JOptionPane.ERROR_MESSAGE);
        }else if(txt_nrIndikator.getText().trim().equals("") || txt_nrIndikator.getText() == null){
            JOptionPane.showMessageDialog(this, "Kolom Nomor Urut Tidak Boleh Kosong", "Eror", JOptionPane.ERROR_MESSAGE);
        }else if(txt_Indikator.getText().trim().equals("") || txt_Indikator.getText() == null){
            JOptionPane.showMessageDialog(this, "Kolom Indikator Tidak Boleh Kosong", "Eror", JOptionPane.ERROR_MESSAGE);
        }else{
            int nrIndikator = Integer.parseInt(txt_nrIndikator.getText());
            String indikator = txt_Indikator.getText();
            
            k_inke = new IndikatorKegiatan(k_kedip, nrIndikator, indikator);
        }
        
        
            
    }
    
    void updateData(){
        k_inke.setIndikator(txt_Indikator.getText());
    }
    
    void clearData(){
        txt_Indikator.setText("");
        txt_Kedip.setText("");
        txt_nrIndikator.setText("");
        k_kedip = null;
        k_inke = new IndikatorKegiatan();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Kedip = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        txt_nrIndikator = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Indikator = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Kegiatan DIPA :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nomor Urut :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Indikator :");

        txt_Kedip.setEditable(false);

        btnBrowse.setText("...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        txt_Indikator.setColumns(20);
        txt_Indikator.setRows(5);
        jScrollPane1.setViewportView(txt_Indikator);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Kedip, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowse))
                            .addComponent(txt_nrIndikator, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Kedip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nrIndikator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSave.setText("Save");
        btnSave.setPreferredSize(new java.awt.Dimension(65, 23));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(isNew){
            getData();
            try {
                k_panel.save(k_inke, isNew);
            } catch (KeudaException ex) {
                Logger.getLogger(IndikatorKegiatanCreateUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
            clearData();
            dispose();
        }else{
            updateData();
            try {
                k_panel.save(k_inke, isNew);
            } catch (KeudaException ex) {
                Logger.getLogger(IndikatorKegiatanCreateUpdate.class.getName()).log(Level.SEVERE, null, ex);
            }
            clearData();
            dispose();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        k_dipaList = new KegiatanDipaListDialog(k_panel.k_mainForm);
        k_dipaList.setVisible(true);
        
        if(k_dipaList.getKegiatanDipa() != null){
            k_kedip = k_dipaList.getKegiatanDipa();
            k_kedip.setView(KegiatanDipa.VIEW_PROGRAM);
            txt_Kedip.setText(""+k_kedip);
        }
        
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearData();
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_Indikator;
    private javax.swing.JTextField txt_Kedip;
    private javax.swing.JTextField txt_nrIndikator;
    // End of variables declaration//GEN-END:variables
}
