/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.keuda.view;

import com.keuda.exception.KeudaException;
import com.keuda.model.Kegiatan;
import com.keuda.model.Program;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class KegiatanDialog extends javax.swing.JDialog {
    Program k_program;
    Kegiatan k_kegiatan;
    ProgramListDialog programListDialog;
    MainForm mainForm;
    KegiatanPanel panel;
    long programIndex;
    /**
     * Creates new form KegiatanDialog
     */
    public KegiatanDialog(KegiatanPanel panel, boolean modal) {
        super(panel.k_mainForm, modal);
        mainForm = panel.k_mainForm;
        this.panel = panel;
        k_kegiatan = new Kegiatan();
        k_program = new Program();
        initComponents();
        programIndex = -1;
        txt_kegiatanname.setLineWrap(true);
        txt_kegiatanname.setWrapStyleWord(true);
        setLocationRelativeTo(null);
    }
    //if dialog Edit
    public KegiatanDialog(KegiatanPanel panel, Kegiatan kgt){
        super(panel.k_mainForm, true);
        this.panel = panel;
        initComponents();
        k_kegiatan = kgt;
        
        txt_program.setText(""+k_kegiatan.getProgram());
        txt_kegiatanname.setText(k_kegiatan.getKegiatanName());
        txt_kegiatancode.setText(k_kegiatan.getKegiatanCode());
        programIndex = k_kegiatan.getProgramIndex();
        txt_kegiatanname.setLineWrap(true);
        txt_kegiatanname.setWrapStyleWord(true);
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_kegiatancode = new javax.swing.JTextField();
        txt_program = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_kegiatanname = new javax.swing.JTextArea();
        btnBatal = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add/Edit Kegiatan");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Kegiatan"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Program :");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Kode Kegiatan :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nama Kegiatan :");

        txt_program.setEditable(false);

        btnBrowse.setText("...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        txt_kegiatanname.setColumns(20);
        txt_kegiatanname.setRows(5);
        jScrollPane1.setViewportView(txt_kegiatanname);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_kegiatancode)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_program, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBrowse))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_program, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_kegiatancode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        programListDialog = new ProgramListDialog(mainForm);
            programListDialog.setVisible(true);
            
//            k_kegiatan.setProgram(programListDialog.getProgram());
//            k_kegiatan.setProgramIndex(k_program.getProgramIndex());
            if(programListDialog.getProgram() != null){
                k_program = new Program(programListDialog.k_obj);   
                programIndex = k_program.getProgramIndex();
                k_program.setView(Program.VIEW_CODE_AND_NAME);
                txt_program.setText(""+k_program);
            }else{
                return;
            }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
            String name = "";
            String code = "";
            
            name = txt_kegiatanname.getText();
            code = txt_kegiatancode.getText();
                if(txt_program.getText().trim().equals("") || txt_program.getText()==null){
                    JOptionPane.showMessageDialog(null, "Program tidak boleh kosong", "Peringatan", JOptionPane.ERROR_MESSAGE);
                    return ;
                }else if(code == null || code.trim().equals("")){
                    JOptionPane.showMessageDialog(null, "Kode Kegiatan tidak boleh kosong", "Peringatan", JOptionPane.ERROR_MESSAGE);
                    return ;
                }else if(name == null || name.trim().equals("")){
                    JOptionPane.showMessageDialog(null, "Nama Kegiatan tidak boleh kosong", "Peringatan", JOptionPane.ERROR_MESSAGE);
                    return ;
                }else{
                    k_kegiatan.setKegiatanCode(code);
                    k_kegiatan.setKegiatanName(name);
                    k_kegiatan.setProgramIndex(programIndex);
                    try {
                        panel.save(k_kegiatan);
                    } catch (KeudaException ex) {
                        Logger.getLogger(KegiatanDialog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                
                dispose();
                
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    public Kegiatan getK_kegiatan() {
        return k_kegiatan;
    }

    public void setK_kegiatan(Kegiatan k_kegiatan) {
        this.k_kegiatan = k_kegiatan;
    }

    public void setProgramIndex(long programIndex) {
        this.programIndex = programIndex;
    }
    
    
    
    public Program getK_program() {
        return k_program;
    }

    public void setK_program(Program k_program) {
        this.k_program = k_program;
    }
    
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_kegiatancode;
    private javax.swing.JTextArea txt_kegiatanname;
    private javax.swing.JTextField txt_program;
    // End of variables declaration//GEN-END:variables

    
}
