/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.keuda.view;

import com.keuda.Logic.BusinessLogic;
import com.keuda.exception.KeudaException;
import com.keuda.model.Program;
import com.keuda.model.ProgramDipa;
import com.keuda.services.IDBCConstant;
import com.keuda.util.PanelButton;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class ProgramDipaPanel extends javax.swing.JPanel implements ListSelectionListener{

    /**
     * Creates new form ProgramDipaPanel
     */
    BusinessLogic k_logic;
    ProgramDipaTableModel k_tmodel;
    long sessionId;
    Connection k_conn;
    ProgramDipa k_ProgramDipa;
    ProgramDipaDialog dialogProgramDipa;
    MainForm k_form;
    
    public ProgramDipaPanel(MainForm k_mainForm) throws KeudaException {
        
        initComponents();
        k_conn = k_mainForm.k_conn;
        k_form = k_mainForm;
        k_tmodel = new ProgramDipaTableModel();
        sessionId = k_mainForm.k_sessionId;       
        
        tableProgramDipa.setModel(k_tmodel);
        tableProgramDipa.getTableHeader().setReorderingAllowed(false);
        
        tableProgramDipa.getTableHeader().resizeAndRepaint();
        tableProgramDipa.getSelectionModel().addListSelectionListener(this);
        tableProgramDipa.getColumnModel().getColumn(0).setMaxWidth(100);
        tableProgramDipa.getColumnModel().getColumn(0).setMinWidth(100);
        tableProgramDipa.getColumnModel().getColumn(1).setMaxWidth(100);
        tableProgramDipa.getColumnModel().getColumn(1).setMinWidth(100);
        tableProgramDipa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableProgramDipa.setRowHeight(20);
        
        
        btn_hapus.setEnabled(false);
        btn_cetak.setEnabled(false);
        init();
    }

    private void init() throws KeudaException {
        k_tmodel.setRowCount(0);
        k_logic = new BusinessLogic(k_conn);
        ProgramDipa[] list = k_logic.getAllProgramDipa(sessionId, IDBCConstant.MODUL_CONFIGURATION);
        if(list != null){
            for(int i=0; i<list.length; i++){
                ProgramDipa program = list[i];
                program.getProgram().setView(Program.VIEW_CODE);
                program.setView(ProgramDipa.VIEW_PROGRAM);
                k_tmodel.addRow(new Object[]{program, program.getTahunAnggaran(),program.getProgram().getProgramName()});
            }
        }
        btn_hapus.setEnabled(false);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if(!e.getValueIsAdjusting()){
            int iRowIndex = ((ListSelectionModel)e.getSource()).getMinSelectionIndex();
            
            if(iRowIndex != -1){
                Object obj = tableProgramDipa.getValueAt(iRowIndex, 0);
                k_ProgramDipa = (ProgramDipa) obj;
                btn_hapus.setEnabled(true);
            }
        }
    }

    
    public class ProgramDipaTableModel extends DefaultTableModel{

        public ProgramDipaTableModel() { 
            addColumn("Kode Program");
            addColumn("Tahun Anggaran");
            addColumn("Program");
            
        }

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        
        
        
        @Override
        public int getColumnCount() {
            return 3;
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProgramDipa = new javax.swing.JTable();
        btn_cetak = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableProgramDipa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableProgramDipa);

        btn_cetak.setText("Cetak");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cetak)
                    .addComponent(btn_hapus)
                    .addComponent(btn_tambah))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        dialogProgramDipa = new ProgramDipaDialog(k_form, true);
        dialogProgramDipa.setLocationRelativeTo(null);
        dialogProgramDipa.setVisible(true);
        try {
            init();
        } catch (KeudaException ex) {
            Logger.getLogger(ProgramDipaPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int panel = -1;
        panel = JOptionPane.showConfirmDialog(btn_hapus, "Apakah anda yakin akan menghapus : \n"+k_ProgramDipa.getProgram().getProgramName(), "Perhatian", JOptionPane.OK_CANCEL_OPTION);
        
        if(panel == JOptionPane.OK_OPTION){
            k_logic = new BusinessLogic(k_conn);
            try {
                k_logic.deleteProgramDipa(k_ProgramDipa.getDipaIndex(), sessionId, IDBCConstant.MODUL_CONFIGURATION);
                init();
            } catch (KeudaException ex) {
                Logger.getLogger(ProgramDipaPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            return ;
        }
        
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        
    }//GEN-LAST:event_btn_cetakActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProgramDipa;
    // End of variables declaration//GEN-END:variables
}
