/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.keuda.view;

import com.keuda.Logic.BusinessLogic;
import com.keuda.exception.KeudaException;
import com.keuda.model.Akun;
import com.keuda.model.Dipa;
import com.keuda.model.Markmap;
import com.keuda.model.Rincian;
import com.keuda.model.SubKomponen;
import com.keuda.services.IDBCConstant;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author adam
 */
public class RincianAkunDialog extends javax.swing.JDialog {
    CboTahunModel cboTahunModel;
    CboNodipModel cboNodipModel;
    Rincian k_rincian;
    Markmap markmap;
    SubKomponen k_subkomponen;
    Object k_obj;
    int k_tahun = 0;
    Dipa k_dipa;
    MainForm k_mainForm;
    MarkmapListDialog markmapListDialog;
    BusinessLogic k_logic;
    /**
     * Creates new form RincianAkunDialog
     */
    public RincianAkunDialog(MainForm parent, SubKomponen subkomp,  boolean modal) {
        super(parent,"Add/Edit Rincian", modal);
        k_mainForm = parent;
        initComponents();
        this.k_subkomponen = subkomp;
        cboTahunModel = new CboTahunModel();
        cboNodipModel = new CboNodipModel();
        cboTahun.setModel(cboTahunModel);
        cboNodip.setModel(cboNodipModel);
        k_logic = new BusinessLogic(parent.getK_conn());
        setLocationRelativeTo(null);
    }
    
    public RincianAkunDialog(MainForm parent, SubKomponen subkomp, Rincian rincian,boolean edit) {
        super(parent, true);
        initComponents();
        k_rincian = rincian;
        k_subkomponen = subkomp;
        cboTahunModel = new CboTahunModel();
        cboNodipModel = new CboNodipModel();
        cboTahun.setModel(cboTahunModel);
        cboNodip.setModel(cboNodipModel);
    }
    
    public void initDataComboDipa(int tahun){
        
        BusinessLogic logic = new BusinessLogic(k_mainForm.k_conn);
        cboNodipModel.removeAllElements();
        
        if(tahun != -1 || tahun > 0){
            Dipa list = null;
            try {
                list = logic.getAllDipaByTahunAnggaran(tahun, k_mainForm.k_sessionId, IDBCConstant.MODUL_CONFIGURATION);
            } catch (KeudaException ex) {
                Logger.getLogger(RincianAkunDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            cboNodipModel.addElement("");
                list.setView(Dipa.VIEW_NOMOR_DIPA);
                cboNodipModel.addElement(list);
        }else{
            cboNodipModel.addElement("");
        }
    }
    
    public class CboTahunModel extends DefaultComboBoxModel{

        public CboTahunModel() {
            addElement("");
            addElement("2014");
            addElement("2015");
        }
        
    }
    
    public class CboNodipModel extends DefaultComboBoxModel{

        public CboNodipModel() {
            addElement("");
            addElement("DIPA-010.09.1.662766/2014");
        }
        
    }
    
    public void collectData(){
        if(cboTahun.getSelectedItem().toString().trim().equals("")){
            JOptionPane.showMessageDialog(this, "Tahun Belum Dipilih", "Perhatian", JOptionPane.ERROR_MESSAGE);
        }else if(cboNodip.getSelectedItem() == null){
            JOptionPane.showMessageDialog(this, "Nomor DIPA Belum Dipilih.", "Perhatian", JOptionPane.ERROR_MESSAGE);
        }else if(txt_akun.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Akun Belum Dipilih", "Perhatian", JOptionPane.ERROR_MESSAGE);
        }else{
            k_rincian = new Rincian(k_subkomponen, k_dipa);
            k_rincian.setKoderekening(markmap.getKdrekening());
            k_rincian.setNamarekening(markmap.getNmrekening());
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboTahun = new javax.swing.JComboBox();
        cboNodip = new javax.swing.JComboBox();
        txt_akun = new javax.swing.JTextField();
        btnbrowse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        btnbatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Tahun :");

        jLabel3.setText("No. DIPA :");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Akun :");

        cboTahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2014", "2015" }));
        cboTahun.setPreferredSize(new java.awt.Dimension(0, 23));
        cboTahun.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTahunItemStateChanged(evt);
            }
        });
        cboTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTahunActionPerformed(evt);
            }
        });

        cboNodip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DIPA-010.09.1.662766/2014" }));
        cboNodip.setEnabled(false);
        cboNodip.setPreferredSize(new java.awt.Dimension(0, 23));
        cboNodip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNodipItemStateChanged(evt);
            }
        });
        cboNodip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNodipActionPerformed(evt);
            }
        });

        txt_akun.setEditable(false);
        txt_akun.setPreferredSize(new java.awt.Dimension(6, 23));

        btnbrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/keuda/images/search.png"))); // NOI18N
        btnbrowse.setEnabled(false);
        btnbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_akun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbrowse))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboNodip, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboNodip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbrowse)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txt_akun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/keuda/images/save.gif"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setPreferredSize(new java.awt.Dimension(90, 23));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnsimpan);

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/keuda/images/cancel.gif"))); // NOI18N
        btnbatal.setText("Batal");
        btnbatal.setPreferredSize(new java.awt.Dimension(90, 23));
        btnbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbatalActionPerformed(evt);
            }
        });
        jPanel2.add(btnbatal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboNodipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNodipActionPerformed
        
    }//GEN-LAST:event_cboNodipActionPerformed

    private void cboNodipItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNodipItemStateChanged
        if(cboNodip.getSelectedItem() != null){
            Object obj = cboNodip.getSelectedItem();
            if(obj instanceof Dipa){
                k_dipa = (Dipa) obj;
                btnbrowse.setEnabled(true);
            }else{
                k_dipa = null;
                btnbrowse.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cboNodipItemStateChanged

    private void cboTahunItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTahunItemStateChanged
        if(!cboTahun.getSelectedItem().toString().equals("")){
            k_tahun = Integer.valueOf(cboTahun.getSelectedItem().toString().trim());
            initDataComboDipa(k_tahun);
            cboNodip.setEnabled(true);
        }else{
            k_tahun = 0;
            initDataComboDipa(k_tahun);
            cboNodip.setEnabled(false);
        }
    }//GEN-LAST:event_cboTahunItemStateChanged

    private void cboTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTahunActionPerformed
        
    }//GEN-LAST:event_cboTahunActionPerformed

    private void btnbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrowseActionPerformed
        markmapListDialog = new MarkmapListDialog(k_mainForm);
        markmapListDialog.setVisible(true);
        if(markmapListDialog.getMarkmap() != null){
            markmap = markmapListDialog.getMarkmap();
            String value = markmap.getKdrekening().trim()+"  "+markmap.getNmrekening().trim();
            txt_akun.setText(value);
        }else{
            txt_akun.setText("");
            markmap = null;
        }
    }//GEN-LAST:event_btnbrowseActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        collectData();
        try {
            k_logic.createRincian(k_rincian, k_mainForm.k_sessionId, IDBCConstant.MODUL_CONFIGURATION);
            dispose();
        } catch (KeudaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnbatalActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbatal;
    private javax.swing.JButton btnbrowse;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox cboNodip;
    private javax.swing.JComboBox cboTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_akun;
    // End of variables declaration//GEN-END:variables
}
