package com.keuda.view;

import com.keuda.Logic.BusinessLogic;
import com.keuda.exception.KeudaException;
import com.keuda.model.Satker;
import com.keuda.services.IDBCConstant;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author BENDAHARA
 */
public class SPPInputDialog extends javax.swing.JDialog {

    /**
     * Creates new form SPPInputDialog
     */
    MainForm k_MainForm;
    
    ComboSatkerModel cbosatkermodel;
    ComboJenisModel cbojenismodel;
    ComboTahunAnggaranModel cbothangmodel;
    public SPPInputDialog(MainForm form, boolean modal) {
        super(form, modal);
        initComponents();
        k_MainForm = form;
        
        cbosatkermodel = new ComboSatkerModel();
        cbojenismodel = new ComboJenisModel();
        cbothangmodel = new ComboTahunAnggaranModel();
        
        cbo_satker.setModel(cbosatkermodel);
        cbo_jenisspp.setModel(cbojenismodel);
        cbo_thang.setModel(cbothangmodel);
        
        cbo_jenisspp.setEnabled(false);
        cbo_thang.setEnabled(false);
        
        cbo_satker.addItemListener(cbosatkermodel);
        cbo_jenisspp.addItemListener(cbojenismodel);
        cbo_thang.addItemListener(cbothangmodel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbo_satker = new javax.swing.JComboBox();
        cbo_jenisspp = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbo_thang = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail SPP"));

        jLabel1.setText("Satker :");

        jLabel2.setText("Jenis SPP :");

        cbo_satker.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbo_jenisspp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Tahun Anggaran :");

        cbo_thang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbo_jenisspp, 0, 410, Short.MAX_VALUE)
                            .addComponent(cbo_satker, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbo_thang, 0, 410, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbo_satker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_jenisspp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPPInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPPInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPPInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPPInputDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SPPInputDialog dialog = null;
                try {
                    dialog = new SPPInputDialog(new MainForm(), true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SPPInputDialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(SPPInputDialog.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(SPPInputDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private class ComboSatkerModel extends DefaultComboBoxModel implements ItemListener{
        BusinessLogic logic = null;
        public ComboSatkerModel() {
            logic = new BusinessLogic(k_MainForm.k_conn);
            Satker[] listSatker = null;
            try {
                listSatker = logic.getAllSatker(k_MainForm.k_sessionId, IDBCConstant.MODUL_CONFIGURATION);
            } catch (KeudaException ex) {
                Logger.getLogger(SPPInputDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            addElement("");
            if(listSatker != null){
                for (int i = 0; i<listSatker.length; i++){
                    Satker satker=listSatker[i];
                    satker.setView(satker.VIEW_NAME_AND_CODE_SATKER);
                    addElement(satker);
                }
            }
        }

        @Override
        public void itemStateChanged(ItemEvent e) {
            if(!cbo_satker.getSelectedItem().equals("")){
                cbo_jenisspp.setEnabled(true);
                cbo_thang.setEnabled(false);
                       
            }else{
                
                cbo_jenisspp.setEnabled(false);
                cbo_jenisspp.setSelectedIndex(0);
                cbo_thang.setEnabled(false);
                cbo_thang.setSelectedIndex(0);
            }
        }
        
    }
    
    private class ComboJenisModel extends DefaultComboBoxModel implements ItemListener{

        public ComboJenisModel() {
            addElement("");
            addElement("SPP UP");
        }

        @Override
        public void itemStateChanged(ItemEvent e) {
            if(!cbo_jenisspp.getSelectedItem().equals("")){
                cbo_thang.setEnabled(true);
            }else{
                cbo_thang.setEnabled(false);
                cbo_thang.setSelectedIndex(0);
            }
        }
        
    }
    
    private class ComboTahunAnggaranModel extends DefaultComboBoxModel implements ItemListener{

        public ComboTahunAnggaranModel() {
            addElement("");
            addElement("2014");
            addElement("2015");
        }

        @Override
        public void itemStateChanged(ItemEvent e) {
            
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbo_jenisspp;
    private javax.swing.JComboBox cbo_satker;
    private javax.swing.JComboBox cbo_thang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
